### ISSUE TITLE
No TS support?

### ISSUE THREAD

**Issue by decipher-cs** [oslabs-beta/Zusty#45]
`import zustymiddleware from 'zustymiddleware'` throws the following error: 
```
Could not find a declaration file for module 'zustymiddleware'. 'node_modules/.pnpm/zustymiddleware@1.2.0/node_modules/zustymiddleware/index.js' implicitly has an 'any' type. Try `npm i --save-dev @types/zustymiddleware` if it exists or add a new declaration (.d.ts) file containing `declare module 'zustymiddleware';` [7016]
```

Is there going to be support for it in the future?

```
React: v18.2
Zustand: v4.5
Typescript: v5.2
zustymiddleware: v1.2.0
```

**Comment by DanaKaplan944** [comment]
Thanks for bringing this up. We are working to add Typescript support and will have an update soon!

**Comment by JaeBrian** [comment]
Hey deciper-cs, we just implemented Zusty for TypeScript, if you follow the README, you will find our new npm module for Typescript and how to implement it for Typescript. Let us know if you have any other issues, thank you!

@decipher-cs

**Comment by decipher-cs** [comment]
Hate to be the bearer of bad news but it doesn't work. Here's the error I got after copying the example from your [npm's readme](https://www.npmjs.com/package/zustymiddlewarets?activeTab=readme#usage) verbatim.
```
Argument of type 'Middleware' is not assignable to parameter of type 'StateCreator<BearState, [], [], BearState>'.
  Type 'Middleware' is not assignable to type '(setState: (partial: BearState | Partial<BearState> | ((state: BearState) => BearState | Partial<BearState>), replace?: boolean | undefined) => void, getState: () => BearState, store: StoreApi<...>) => BearState'.
    Type 'Store' is missing the following properties from type 'BearState': bears, increase, removeAllBearstypescript(2345)
  ```
  
Here's a sandbox. [codesandbox](https://codesandbox.io/p/sandbox/rusty-zusty-dvj7np?file=%2Fsrc%2FzustyStore.ts%3A5%2C16)

**Comment by DanaKaplan944** [comment]
Hi @decipher-cs thanks for the sandbox and letting us know. The TS middleware has now been fixed. Let us know if you have any further issues.
